### ISSUE TITLE
[Bug] Change node name: view not refreshing

### ISSUE THREAD

**Issue by stefan-wolfsheimer** [vantage6/vantage6-UI#71]
**Describe the bug**
After changing the name of a node the new value is not refreshed in the list

**To Reproduce**
1. Go to Nodes and select a node from the list
2. Click on 'Change name' and enter a new name (See screenshot 1)
3. Click 'Edit'
4. Click on another main menu item (e.g. 'Users')
5. Go to Nodes (See screenshot 2)

**Expected behavior**
The new node name appears in the list.
The label of the button is misleading: Should be "save" instead of "edit".

**Actual behavior** 
The old node name appears in the list. 
After reloading (navigating to root via the url bar) the new node name appears as expected. 

**Screenshots**
Screenshot 1: (after step 2)
![vnt6node](https://user-images.githubusercontent.com/4751637/196455188-e110ff8e-5cf7-4740-8ca6-15b2026b672c.png)

Screenshot 1: (after step 5)
![vnt6node2](https://user-images.githubusercontent.com/4751637/196455886-8ec38eb7-521c-4f11-a620-0eda08035f1f.png)

**Context **
browser: chrome (latest version)

**Comment by bartvanb** [comment]
Hi Stefan, can you detail which version of the UI you are using? I can't reproduce this with the latest version; there is a chance we fixed this already last week.

Are you using the docker image we provide on `harbor2.vantage6.ai/infrastructure/ui`? In that case, please pull a new image (I just updated this). We do not yet automatically update that image when we release a new version - I've just added the new images manually and create issue #72 to improve this process soon.

**Comment by stefan-wolfsheimer** [comment]
Hi Bart,

I build the image myself from this tag:
https://github.com/vantage6/vantage6-UI/tree/version/3.3.7

The version displayed in the UI is wrong:
https://github.com/vantage6/vantage6-UI/blob/version/3.3.7/package.json#L3


When a node gets online, I observe a similar issue: The node is still displayed as offline in the UI. When navigating back to the root and going back to the node view, it is labeled correctly labeled as "online." 

Maybe I should use the 3.3.7-post2 tag or just use the image from your registry.

**Comment by bartvanb** [comment]
Hi Stefan,

Yes I think using the `3.3.7-post2` tag might resolve your issue. Contrary to what you might expect, there are code changes between 3.3.7 and 3.3.7-post2: we are trying to align versions between the infrastructure code and the UI, but when we release a UI in between, we use post tags -- maybe we should switch to something like 3.3.7.2

Regarding the node that gets online: you are right that the view in the UI is not updated currently as the server response (which includes online/offline status) is cached. We plan to connect the UI to the websocket (#73) and then we can properly update node status via socket connect events.

**Comment by stefan-wolfsheimer** [comment]
Hi Bart,

I tried it with 3.3.7-post3 (building myself) and pulled it from the registry, but the error is still there.
Since you are planning a bigger change, should put this issue on the backlog and check it again when the websocket is implemented?

Kind regards,

Stefan

**Comment by bartvanb** [comment]
Sorry Stefan -- just figured out I tried to read your steps to reproduce too quickly. When I did, I was indeed able to reproduce it, and just opened the PR to resolve this. So it should be resolved soon

**Comment by bartvanb** [comment]
Released in 3.4.0
